default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: <%= ENV['DATABASE_URL_DEVELOPMENT'] %>

test:
  <<: *default
  database: retoapp_test
  username: postgres
  password: password
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL_PRODUCTION'] %>
