default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: <%= ENV['DATABASE_URL_DEVELOPMENT'] %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL_TEST'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL_PRODUCTION'] %>
